// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtrwlxicgrfhpwnukrhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0cndseGljZ3JmaHB3bnVrcmhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3ODYwNTMsImV4cCI6MjA1MDM2MjA1M30.LMLp2keAp5CIdlnp_OlUNFjgYB-iJov4RUdMzpclXyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);